### ISSUE TITLE
Help: 3 hue Lamps in a row at top_center

### ISSUE THREAD

**Issue by 346marcel** [michael5r/mmm-hue-lights#13]
Hi,

so i am having 3 hue Lights (4, with 1 hidden) and i am trying to line them up in a row at Top_center.

Can someone help me?

I tried this in the custom.css but no success:

.mmm-hue-lights .grid {
    width: auto; // do i have to adapt the width manually?
    display: flex;
    flex-direction: row;	
    flex-wrap: nowrap;	//cause i want no wrap	
    margin: -10px;
    max-width: auto;		// adapt this too?
    justify-content: center;
    align-items: center;	
}

.mmm-hue-lights .grid .hue {
    //float: left; 		//test
    width: calc(33.33% - 20px);  //like in your example or does this have to be 33.33% of the top_center?
    margin: 10px;
    display: block;
}

**Comment by michael5r** [comment]
@346marcel This is what I use to get 3 lights in a row:

```
.mmm-hue-lights .grid {
    width: auto;
    display: flex;
    flex-flow: row wrap;
    margin: -10px;
    max-width: none;
    justify-content: center;
}

.mmm-hue-lights .grid .hue {
    width: calc(33.33% - 20px);
    margin: 10px;
    display: block;
}
```
