### ISSUE TITLE
API ERROR: Error: Read ECONNRESET

### ISSUE THREAD

**Issue by jasimi** [michael5r/mmm-hue-lights#18]
I installed mmm-hue-lights by default and get the following error message after 5 minutes. Hue API ERROR: Error: Read ECONNRESET. I ask for help with this problem. I've already reinstalled everything and it doesn't help.

**Comment by jasimi** [comment]
![2020-04-24 13 24 13](https://user-images.githubusercontent.com/61836987/80210535-355e1100-8634-11ea-81be-be0a41786f4f.jpg)

**Comment by jasimi** [comment]
![2020-04-24 13 23 49](https://user-images.githubusercontent.com/61836987/80210591-4ad33b00-8634-11ea-8b92-63b32cff4acf.jpg)

**Comment by michael5r** [comment]
I've released a new `1.4.0` version of this module that will hopefully help with the refresh issue - it now automatically reschedules an update, no matter whether there's an error or not.

Please download the version and see if that solves your issue.
