### ISSUE TITLE
Refresh Issue

### ISSUE THREAD

**Issue by alepelc** [michael5r/mmm-hue-lights#7]
On load, the lights are shown correctly but when the refresh kicks in, I got error like Hue API Error: NULL or Sockets Errors. If I refresh the page it is fine until the next auto refresh kicks in.

**Comment by alepelc** [comment]
Sorry for the delay... Initially I was using a small interval, then went back to default. I still have issues and I'm not discarding a networking one, but what I see is that once the issue happens, it will stay until reload the program (not the browser). Probably it's something that keeps hung upon failure and not re-initialized properly again? Will check it out...

**Comment by ElectricCharlie** [comment]
I'm encountering this error as well. The only solution I've found around it is to stop the MagicMirror and restart it. Sometimes it works for weeks, and sometimes it fails after a just a few hours of being connected. Is there a way to restart just the mmm-hue-lights module within MagicMirror? Or a way to recover from network errors?

**Comment by michael5r** [comment]
Thanks for the reports, guys - I have an idea that could possibly help the module recover after this network error. I'll see if I can get it built into this module this week.

**Comment by cutzenfriend** [comment]
+1 Same issue here. Network is surely not the issue. I also tried multiple update intervals. from 1 to 60 minutes.

**Comment by bobybob69** [comment]
+1 Same issue here . Don't understand from where the issue is coming from. I tried different refresh time .. but same error. 

Error : read ECONNRESET
Hue API error : NULL

Thanks for looking at it

**Comment by JohnLucaJF** [comment]
did this ever get resolved. I set it up recently and worked perfectly for a day or so and now fails immediately when restarting mm. Gonna set up a new user and see if that resolves. but can access developer with existing user , so doubt it will make any difference

**Comment by michael5r** [comment]
I've released a new `1.4.0` version of this module that will hopefully help with the refresh issue - it now automatically reschedules an update, no matter whether there's an error or not.

Please download the version and see if that solves your issue.
