### ISSUE TITLE
Alignment issue when using with other modules

### ISSUE THREAD

**Issue by MillorHD** [michael5r/mmm-hue-lights#8]
My problem is, that I wanted to display my Hue-lights in a list view with this module directly below a weather-forecast module in the top-left region. Because the weather module is slightly wider than the Hue module, all my lights are aligned to the left and I want them to be as far to the right as possible. I already tried to change the CSS to get this working but I could only make it worse. I hope this is just a mistake by me and not a problem with the module itself so please correct me if made anything wrong.
You can also see the problem on the screenshot below.
![Screenshot](https://user-images.githubusercontent.com/42939710/50861755-f3a34b80-1399-11e9-91b0-7bf2eea7d488.png)

**Comment by michael5r** [comment]
Sure, that's easy enough.

Add this to your `custom.css` file to make the lights the same width as the weather module:
```css
.mmm-hue-lights .grid {
    max-width: none;
}
```
